#The car evaluation dataset is collected from UCI Machine Learning Repository and the data source (creator) was Marko Bohanec [1]. It contains 1728 car sample information with 7 attributes, including one class feature that tells whether the car is in acceptable conditions. The feature names with their descriptions are listed following:

buying_price: Buying Level or Capacity of the customer (Very High: vhigh, High: high, Low: low, Medium: med)
maint_cost: Maintenence Level (Very High: vhigh, High: high, Low: low, Medium: med)
doors: Number of doors in the car (2, 3, 4, and 5 or more)
person_capacity: capacity in terms of persons to carry (2, 4, and more)
lug_boot: The size of the Luggage Boot (small, med, big)
safety: Safety Level of Car (high, med, low)
class: Unacceptable, Acceptable, VeryGood, Good

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
df=pd.read_csv('/content/car_evaluation.csv')

In [ ]:
df

buying price maintenance cost number of doors number of persons lug_boot  \
0           vhigh            vhigh               2                 2    small   
1           vhigh            vhigh               2                 2    small   
2           vhigh            vhigh               2                 2    small   
3           vhigh            vhigh               2                 2      med   
4           vhigh            vhigh               2                 2      med   
...           ...              ...             ...               ...      ...   
1723          low              low           5more              more      med   
1724          low              low           5more              more      med   
1725          low              low           5more              more      big   
1726          low              low           5more              more      big   
1727          low              low           5more              more      big   

     safety decision  
0       low    unacc  
1       med    unacc  
2      high    unacc  
3       low    unacc  
4       med    unacc  
...     ...      ...  
1723    med     good  
1724   high    vgood  
1725    low    unacc  
1726    med     good  
1727   high    vgood  

[1728 rows x 7 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   buying price       1728 non-null   object
 1   maintenance cost   1728 non-null   object
 2   number of doors    1728 non-null   object
 3   number of persons  1728 non-null   object
 4   lug_boot           1728 non-null   object
 5   safety             1728 non-null   object
 6   decision           1728 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


In [ ]:
df.head()

buying price maintenance cost number of doors number of persons lug_boot  \
0        vhigh            vhigh               2                 2    small   
1        vhigh            vhigh               2                 2    small   
2        vhigh            vhigh               2                 2    small   
3        vhigh            vhigh               2                 2      med   
4        vhigh            vhigh               2                 2      med   

  safety decision  
0    low    unacc  
1    med    unacc  
2   high    unacc  
3    low    unacc  
4    med    unacc

In [ ]:
df.describe().T

count unique    top  freq
buying price       1728      4  vhigh   432
maintenance cost   1728      4  vhigh   432
number of doors    1728      4      2   432
number of persons  1728      3      2   576
lug_boot           1728      3  small   576
safety             1728      3    low   576
decision           1728      4  unacc  1210

In [ ]:
df.shape

(1728, 7)

In [ ]:
df.count()

buying price         1728
maintenance cost     1728
number of doors      1728
number of persons    1728
lug_boot             1728
safety               1728
decision             1728
dtype: int64

In [ ]:
df.isnull().sum()

buying price         0
maintenance cost     0
number of doors      0
number of persons    0
lug_boot             0
safety               0
decision             0
dtype: int64

In [ ]:
X=df.drop(['decision'],axis=1)
y=df['decision']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.30,random_state  = 101)

In [ ]:
pip install category_encoders

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import category_encoders as ce


In [ ]:
# encode variables with ordinal encoding
encoder = ce.OrdinalEncoder(cols=['buying price', 'maintenance cost', 'number of doors', 'number of persons', 'lug_boot', 'safety'])


In [ ]:
X_train = encoder.fit_transform(X_train)
X_test = encoder.transform(X_test)

In [ ]:
X_train

buying price  maintenance cost  number of doors  number of persons  \
417              1                 1                1                  1   
723              2                 2                2                  2   
1248             3                 1                2                  3   
1092             3                 2                3                  1   
757              2                 1                3                  3   
...            ...               ...              ...                ...   
599              2                 3                2                  3   
1599             4                 2                1                  3   
1361             4                 4                2                  1   
1547             4                 2                4                  3   
863              2                 1                1                  2   

      lug_boot  safety  
417          1       1  
723          1       1  
1248         2       1  
1092         1       1  
757          3       2  
...        ...     ...  
599          1       3  
1599         2       1  
1361         3       3  
1547         2       3  
863          2       3  

[1209 rows x 6 columns]

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
dtree=DecisionTreeClassifier()

In [ ]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier()

In [ ]:
prediction =dtree.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report ,confusion_matrix 

In [ ]:
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

         acc       0.96      0.92      0.94       108
        good       0.86      0.90      0.88        21
       unacc       0.98      0.99      0.98       374
       vgood       0.94      1.00      0.97        16

    accuracy                           0.97       519
   macro avg       0.94      0.95      0.94       519
weighted avg       0.97      0.97      0.97       519



In [ ]:
print(confusion_matrix(y_test,prediction))

[[ 99   0   8   1]
 [  2  19   0   0]
 [  2   3 369   0]
 [  0   0   0  16]]


In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rfc=RandomForestClassifier(n_estimators=600)

In [ ]:
rfc.fit(X_train,y_train)

RandomForestClassifier(n_estimators=600)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

         acc       0.96      0.92      0.94       108
        good       0.86      0.90      0.88        21
       unacc       0.98      0.99      0.98       374
       vgood       0.94      1.00      0.97        16

    accuracy                           0.97       519
   macro avg       0.94      0.95      0.94       519
weighted avg       0.97      0.97      0.97       519



In [ ]:
print(confusion_matrix(y_test,prediction))

[[ 99   0   8   1]
 [  2  19   0   0]
 [  2   3 369   0]
 [  0   0   0  16]]
